### ISSUE TITLE
Remove lorem text

### ISSUE THREAD

**Issue by codelitt** [codelittinc/codelitt#8]
http://www.codelitt.com/technologies

1. Add Golang to every single one of the columns. 

2. The right implementation. A successful product requires lorem ipsum dolor sit amet in tenebris. ---> 

"Startup Software Engineers and Team

A successful product requires the best talent"

@carloscheddar

**Comment by carloscheddar** [comment]
85a54dfc8ce2f37680e08d30646a3ff629dabf30
